AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 3.2
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
    - 'spec/dummy/**/*'
    - 'lib/generators/**/*'
    - 'bin/*'

Layout/LineLength:
  Max: 150

# DISABLED

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
